name: publishing

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Publish - dry run
        run: flutter pub publish --dry-run
        working-directory: ${{ inputs.working-directory }}

# [TBD] Not working by now
#      - name: Publish to pub.dev
#        run: dart pub publish -f
#        working-directory: ${{ inputs.working-directory }}