name: publishing

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Check Wrapper
        run: | 
          flutter pub get
          flutter pub publish --dry-run
        working-directory: ./flutter_gherkin_wrapper

      - name: Check Generator
        run: | 
          flutter pub get
          flutter pub publish --dry-run
        working-directory: ./flutter_gherkin_generator

# [TBD] Not working by now
#      - name: Publish to pub.dev
#        run: dart pub publish -f
#        working-directory: ${{ inputs.working-directory }}