name: testing

on:
  push:
  pull_request:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Check Generator
        run: |
          flutter pub get
          dart format --output=none --set-exit-if-changed .
          flutter analyze
          flutter test
        working-directory: ./flutter_gherkin_generator
          
      - name: Check Wrapper
        run: |
          flutter pub get
          dart format --output=none --set-exit-if-changed .
          flutter analyze
          flutter test
        working-directory: ./flutter_gherkin_wrapper

      - name: Validate
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          flutter test
        working-directory: ./example