name: testing

on:
  push:
  pull_request:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Validate Wrapper
        run: |
          flutter pub get
          dart format --output=none --set-exit-if-changed .
          flutter analyze
          flutter test
        working-directory: $GITHUB_WORKSPACE/flutter_gherkin_wrapper

      - name: Validate Generator
        run: | 
          flutter pub get
          dart format --output=none --set-exit-if-changed .
          flutter analyze
          flutter test
        working-directory: $GITHUB_WORKSPACE/flutter_gherkin_generator