name: flutter_gherkin_wrapper
description: | 
  Gherkin Wrapper is used to improve widget and integration tests with 
  Cucumber / Gherkin notation
version: 1.0.5
homepage: https://github.com/lyskouski/flutter_gherkin_wrapper/tree/main/flutter_gherkin_wrapper
repository: https://github.com/lyskouski/flutter_gherkin_wrapper
issue_tracker: https://github.com/lyskouski/flutter_gherkin_wrapper/issues

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  gherkin: ^2.0.2

dev_dependencies:
  flutter_lints: ^3.0.1
